### ISSUE TITLE
Unity 2017.1 API upgrade crashed the editor

### ISSUE THREAD

**Issue by parkycai** [neuecc/LINQ-to-GameObject-for-Unity#11]
When imported to Unity 2017.1f3, the editor prompt to upgrade the API, but it never finished, always ended up in a crash.

**Comment by neuecc** [comment]
Thanks, I'll check it.

**Comment by neuecc** [comment]
I've upgraded.
https://github.com/neuecc/LINQ-to-GameObject-for-Unity/commit/e8b1e2d09a59c293a88ad010ebe7e273ca7e7d25

I should upload update to AssetStore, thank you.

**Comment by parkycai** [comment]
Confirmed. Thanks for your effort!
