### ISSUE TITLE
Obsolete API

### ISSUE THREAD

**Issue by NoxMortem** [neuecc/LINQ-to-GameObject-for-Unity#12]
After importing the asset from the AssetStore it tells me "The project uses obsolete API".

**Comment by neuecc** [comment]
Yes, it is fixed by this commit https://github.com/neuecc/LINQ-to-GameObject-for-Unity/commit/e8b1e2d09a59c293a88ad010ebe7e273ca7e7d25
I'll upload new package on AssetStore.
