### ISSUE TITLE
Unable to Add() child from prefab

### ISSUE THREAD

**Issue by slimshader** [neuecc/LINQ-to-GameObject-for-Unity#14]
There is a bug in GameObject.Operate.cs line 94:

`if ((parentTransform == null && childTransform == null) || (parentRectTransform == null))`

"||" should be replaced with "&&"

`if ((parentTransform == null && childTransform == null) && (parentRectTransform == null))`

**Comment by neuecc** [comment]
Sorry, I mistook the branch to upload.
Current assetstore's code is completely broken.

Now, I'm re-upload package.

**Comment by neuecc** [comment]
Today, update release has been accepted.
Please try it.
